<a href="https://colab.research.google.com/github/astridesquivel/unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy es una libreria de python
NumPy se utiliza para trabajar con
matrices o arreglos
NumPy es la abreviatura de "Python numnerico"
Tambien tiene funciones para trabajar en el dominio del algebra lineal,la transformada y las matrices
En python tenemos listas que sirven como matrices,pero son lentas de procesar.
NumPy tiene como objetivo proporcionar un objeto de matriz que sea 50 veces mas rapido que las listas tradicionales.



In [1]:
#Primero tenemos que importar la libreria
import numpy

arreglo = numpy.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


NumPy como np
NumPy generalmente se importa bajo el alias np.En python los alias son un nombre alternativo para referirse a la misma coasa

In [2]:
import numpy as np

arreglo = np.array([6,7,8,9,10])
print(arreglo)

[ 6  7  8  9 10]


comprobando la version de NumPy
La cadena de la version se almacena en  el atributo __version__

In [3]:
import numpy as np

print(np.__version__)

2.0.2


NumPy creando matrices
crear un objeto ndarray de NumPy
NumPy se utiliza para trabjar con matrices.El objeto de matriz se llama ndarray.
Podemos crear un NumPy ndarray utilizando la funcion array()

In [4]:
import numpy as np

arreglo = np.array(["raul","ana","kimberly","yazmin"])
print(arreglo)
print(type(arreglo))

['raul' 'ana' 'kimberly' 'yazmin']
<class 'numpy.ndarray'>


Dimensiones en matrices
Una dimension en matrices es un nivel de profundidad de matriz (matrices unidadas)
Una matriz anidada contiene matrices como elementos
Matrices 0-D.Son elementos de una matriz.Cada valor de una matriz es una matriz 0-D.Ejemplo:crea una matriz 0-D con un valor de 42

In [5]:
import numpy as np

arreglo = np.array(42)

print(arreglo)

42


Matrices 1-D
Una matriz que tiene matrices 0-D como elementos se denomina matriz unidimencional o 1-D.
Estas son las matrices mas comunes y basicas.
Ejemplo: Crea una matriz de 1-D que tenga los valores 1,2,3,4,5

In [6]:
import numpy as np

arreglo = np.array([1,2,3,4,5])

print(arreglo)

[1 2 3 4 5]


Matrices 2D
Una matriz que tiene matrices 1-D como elementos se denomina matriz 2-D.
A menudo se utilizan para representar matrices de segundo orden.NumPy tiene un submodulo completo dedicado a operaciones con matrices llamado numpy.mat.
Ejemplo:crea una matriz 2D que con tenga dos matrices con los valores 123 y 456.

In [8]:
import numpy as np

arreglo = np.array([[1,2,3],[4,5,6]])

print(arreglo)

[[1 2 3]
 [4 5 6]]


Matrices 3D
Una matriz que tiene matrices 2D se denomina matriz 3D.
Estas matrices se utilizan para representar una matriz de tercer orden.
Ejemplo:Crea una matriz 3D con dos matrices bidimencionales, ambas cinteniendo dos matrices con los valores 1,2,3 y 4,5,6.

In [10]:
import numpy as np

arreglo = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arreglo)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
